AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM application for garmin_importer

Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Resources:
  GarminImporterFunctionZip:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: garmin_importer/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - Statement:
            - Sid: SMSecretRUPolicy
              Effect: Allow
              Action:
              - secretsmanager:GetSecretValue
              Resource: !Ref GarminCredentials
        - DynamoDBCrudPolicy:
            TableName: !Ref GarminActivitiesTable
        - S3WritePolicy:
            BucketName: !Ref GarminActivitiesBucket
      Events:
        GarminImporterSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
            Name: garmin_importer
            Description: Schedule with which the garmin_importer runs
            Enabled: True

  GarminCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
        Name: garmin_importer/garmin-credentials

  GarminActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: garmin-activities-table
      AttributeDefinitions:
        - AttributeName: Username
          AttributeType: S
        - AttributeName: ActivityTs
          AttributeType: N
      KeySchema:
        - AttributeName: Username
          KeyType: HASH
        - AttributeName: ActivityTs
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  GarminActivitiesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: garmin-importer-activities
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
